title: Ṣəḥufāna Malkəʾ
description: Unpacking the malkəʾ tradition
alt_title: Malkəʾa Gubāʾe

url: https://malkeagubae.com

collections:
  works:
    output: true
  subjects:
    output: false
  manuscripts:
    output: true

defaults:
  - # blog posts
    scope:
      path: "blog"
      type: "posts"
    values:
      layout: "blog/post"
      author: Augustine Dickinson

  - # works
    scope:
      path: "_works"
      type: "works"
    values:
      layout: "main/work"
      subjects: []

  - # manuscript
    scope:
      path: "_manuscripts"
      type: "manuscripts"
    values:
      layout: "main/manuscript"

  - # *
    scope:
      path: ""
    values:
      layout: "main/default"

permalink: pretty

titles_from_headings:
  strip_title: true
  collections: true

feed:
  path: /blog/feed.xml

exclude:
  - CNAME
  - LICENSE
  - README.md
  - build-index.js
  - assets/scripts/fuse/
  - .git*
  - .vscode*
  - CITATION.cff

include:
  - assets/scripts/fuse/dist/fuse.min.js